# Generated by Django 5.0.14 on 2026-09-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Rascunho'), ('PENDING_APPROVAL', 'Aguardando aprovação'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado'), ('CANCELLED', 'Cancelado')], db_index=True, default='DRAFT', max_length=20),
        ),
    ]
