# Generated by Django 5.0.14 on 2026-09-03 05:00

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('quotations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('project_type', models.CharField(choices=[('SYSTEM', 'Sistema'), ('AUTOMATION', 'Automação'), ('WEBSITE', 'Site'), ('PWA', 'PWA'), ('APP', 'Aplicativo'), ('SAAS', 'SaaS'), ('OTHER', 'Outro')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('APPROVED', 'Aprovado'), ('AWAITING_INITIAL_PAYMENT', 'Aguardando pagamento inicial'), ('INITIAL_PAYMENT_CONFIRMED', 'Pagamento inicial confirmado'), ('IN_DEVELOPMENT', 'Em desenvolvimento'), ('DEVELOPMENT_COMPLETED', 'Desenvolvimento concluído'), ('AWAITING_CLIENT_ACCEPTANCE', 'Aguardando aceite do cliente'), ('ACCEPTED', 'Aceito'), ('AWAITING_FINAL_PAYMENT', 'Aguardando pagamento final'), ('FINAL_PAYMENT_CONFIRMED', 'Pagamento final confirmado'), ('DELIVERED', 'Entregue'), ('MAINTENANCE', 'Manutenção')], default='APPROVED', max_length=30)),
                ('expected_delivery_at', models.DateField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='customers.customer')),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='project', to='quotations.quotation')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects_responsible', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects_project',
                'ordering': ['-created_at'],
            },
        ),
    ]
