# Generated by Django 5.0.14 on 2026-09-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Aprovado'), ('AWAITING_INITIAL_PAYMENT', 'Aguardando pagamento inicial'), ('INITIAL_PAYMENT_CONFIRMED', 'Pagamento inicial confirmado'), ('IN_DEVELOPMENT', 'Em desenvolvimento'), ('DEVELOPMENT_COMPLETED', 'Desenvolvimento concluído'), ('AWAITING_CLIENT_ACCEPTANCE', 'Aguardando aceite do cliente'), ('ACCEPTED', 'Aceito'), ('AWAITING_FINAL_PAYMENT', 'Aguardando pagamento final'), ('FINAL_PAYMENT_CONFIRMED', 'Pagamento final confirmado'), ('DELIVERED', 'Entregue'), ('MAINTENANCE', 'Manutenção')], db_index=True, default='APPROVED', max_length=30),
        ),
    ]
