# Generated by Django 5.0.14 on 2026-09-03 23:48

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('documents', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge_type', models.CharField(choices=[('INITIAL', 'Sinal (30%)'), ('FINAL', 'Saldo (70%)'), ('RECURRING', 'Recorrente'), ('SCOPE_CHANGE', 'Alteração de escopo')], max_length=20)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Em processamento'), ('PAID', 'Pago'), ('OVERDUE', 'Vencido'), ('CANCELLED', 'Cancelado'), ('FAILED', 'Falhou')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(choices=[('BOLETO', 'Boleto'), ('CARD', 'Cartão')], max_length=20)),
                ('external_provider', models.CharField(default='mercadopago', max_length=30)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('payment_link', models.URLField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='customers.customer')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='projects.project')),
            ],
            options={
                'db_table': 'finance_charge',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('due_date', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Paga'), ('OVERDUE', 'Vencida'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.document')),
            ],
            options={
                'db_table': 'finance_expense',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('method', models.CharField(max_length=20)),
                ('paid_at', models.DateTimeField()),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.charge')),
            ],
            options={
                'db_table': 'finance_payment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Paga')], default='PENDING', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='projects.project')),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commission', to='finance.payment')),
            ],
            options={
                'db_table': 'finance_commission',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('PROJECT', 'Projeto'), ('RECURRING', 'Recorrente'), ('OTHER', 'Outro')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.CharField(blank=True, max_length=200)),
                ('received_at', models.DateTimeField()),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revenue', to='finance.payment')),
            ],
            options={
                'db_table': 'finance_revenue',
                'ordering': ['-received_at'],
            },
        ),
    ]
