# Generated by Django 5.0.14 on 2026-09-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('finance', '0002_recurringsubscription_charge_recurring_subscription'),
        ('projects', '0002_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Paga')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Paga'), ('OVERDUE', 'Vencida'), ('CANCELLED', 'Cancelada')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='charge',
            index=models.Index(fields=['status', 'due_date'], name='idx_charge_status_due_date'),
        ),
        migrations.AddIndex(
            model_name='recurringsubscription',
            index=models.Index(fields=['status', 'next_billing_date'], name='idx_sub_status_next_billing'),
        ),
    ]
