# Generated by Django 5.0.14 on 2026-09-11 02:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('service_type', models.CharField(choices=[('SYSTEM', 'Sistema'), ('AUTOMATION', 'Automação'), ('WEBSITE', 'Site'), ('PWA', 'PWA'), ('APP', 'Aplicativo'), ('SAAS', 'SaaS'), ('OTHER', 'Outro')], max_length=20)),
                ('budget_range', models.CharField(choices=[('UNDECIDED', 'Ainda não sei'), ('UNDER_5K', 'Até R$ 5 mil'), ('FROM_5K_TO_15K', 'R$ 5 mil a R$ 15 mil'), ('FROM_15K_TO_40K', 'R$ 15 mil a R$ 40 mil'), ('ABOVE_40K', 'Acima de R$ 40 mil')], default='UNDECIDED', max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'Novo'), ('CONTACTED', 'Em contato'), ('QUALIFIED', 'Qualificado'), ('CONVERTED', 'Convertido'), ('DISCARDED', 'Descartado')], db_index=True, default='NEW', max_length=20)),
                ('internal_notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='customers.customer')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_handled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leads_lead',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='leads_status_created_idx')],
            },
        ),
    ]
