# Generated by Django 5.0.14 on 2026-09-14 18:20

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientePotencial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=11, unique=True)),
                ('descricao_projeto', models.TextField()),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
            options={
                'verbose_name': 'cliente potencial',
                'verbose_name_plural': 'clientes potenciais',
                'ordering': ('-created_at',),
            },
        ),
    ]
