# Generated by Django 5.0.14 on 2026-09-04 00:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=30)),
                ('external_event_id', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('RECEIVED', 'Recebido'), ('PROCESSED', 'Processado'), ('FAILED', 'Falhou'), ('IGNORED', 'Ignorado')], default='RECEIVED', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audit_externalwebhookevent',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='externalwebhookevent',
            constraint=models.UniqueConstraint(fields=('provider', 'external_event_id'), name='uq_webhook_event'),
        ),
    ]
