# Generated by Django 5.0.14 on 2026-09-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['channel', 'status'], name='idx_notif_channel_status'),
        ),
    ]
